# Generated by Django 5.2.6 on 2025-09-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('bp', 'Blood Pressure'), ('hr', 'Heart Rate'), ('glucose', 'Glucose'), ('temp', 'Temperature')], max_length=10)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
