# Generated by Django 5.2.6 on 2025-09-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_hospital_user_years_of_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_hospital',
            new_name='hospital',
        ),
    ]
